import { NavBar } from '@/components/NavBar'
import './globals.css'
import { Inter } from 'next/font/google'
import AsideBar from '@/components/AsideBar'
const IMAGEN_URL = process.env.IMAGEN_URL;
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Electro Avenida',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href={IMAGEN_URL + '/Logo'} />
      <body className={inter.className}>
        <NavBar/>
        <div className='flex'>
          <AsideBar />
          {children}
        </div>
        </body>
    </html>
  )
}
